module CUP_TOP(
  input clk, rst_n,
  output [31:0] READDATA,
  output [5:0] OP
);
  wire REGDST, REGWRITE,ALUSRC, MEMWRITE, MEMREAD,MEMTOREG;
  wire [1:0] ALUCONTROL;
  
  DATAPATH DUT0 (.clk(clk), .rst_n(rst_n),
                 .REGDST(REGDST), .REGWRITE(REGWRITE), .ALUSRC(ALUSRC), .ALUCONTROL(ALUCONTROL), .MEMWRITE(MEMWRITE), .MEMREAD(MEMREAD), .MEMTOREG(MEMTOREG),
                 .OP(OP), .READDATA(READDATA)
                );
  CONTROL_UNIT DUT1( .REGDST(REGDST), .REGWRITE(REGWRITE), .ALUSRC(ALUSRC), .ALUCONTROL(ALUCONTROL), .MEMWRITE(MEMWRITE), .MEMREAD(MEMREAD), .MEMTOREG(MEMTOREG),
                    .OP(OP));
endmodule
